### ISSUE TITLE
is only formatting *.sh file?

### ISSUE THREAD

**Issue by agrozyme** [foxundermoon/vs-shell-format#18] opened 2018-07-28 03:36 UTC
I use those setting:

```
  "shellformat.flag": "-i 2 -sr -bn",
  "shellformat.runOnSave": true,
```
Sometimes, when I save REAME.md, it will do format and repace `  with $() .

**Comment by GreenRaccoon23** [comment] 2018-08-03 15:31
I have noticed a similar issue. When I save a file that is in a language other than "Shell Script", an error notification pops up in the lower right which says:

```text
shell format error:<standard input>:5:21: a command can only contain words and redirects

Source: shell-format (Extension)
```

If I do not have any shell scripts open, the notification does not pop up. But once I do open a shell script (or set the language to "Shell Script"), the notification always pops up. After I close the shell script (or set the language to anything other than "Shell Script"), the notification always pops up.

So it looks like setting the language to "Shell Script" triggers the extension to start running, but setting the language to anything other than "Shell Script" does not trigger the extension to stop running.

**Comment by Kurt-Shiwz** [comment] 2018-08-16 11:10
same problem, how to fix it

**Comment by ahoenle** [comment] 2018-09-20 18:07
Same issue. I also get regular errors when saving python files from `shfmt` on which it should've never run in the first place.

I'm running with the `"shellformat.runOnSave": true` option and I can confirm that it depends on whether or not a `.sh` file was opened before in the workspace.

After reloading the window (shift-cmd-p 'Reload Window) I can save the `.md` file with no problems.

Once I open a `.sh` file my `.md` file gets altered when I save it again.

This behaviour _persists_ even after closing the `.sh` file.

The addon is now trying to `shfmt` every file regardless of its extension on save.

Quick fix to keep on working is of course: Disable the shell format extention and reloading the window.

I hope that #19 will be merged soon!

**Comment by foxundermoon** [comment] 2018-11-28 18:36
on version  2.0.0   replace   `shellformat.runOnSave` with default `editor.formatOnSave`

**Closed** 2018-11-28 18:37 UTC
Labels: bug
